---
name: "Mordomo HA - WhatsApp Bridge"
description: "Ponte WhatsApp para o Mordomo HA. Liga o teu WhatsApp com QR code - sem configuracao adicional."
version: "1.0.6"
slug: "mordomo_bridge"
url: "https://github.com/mentxia/mordomo-ha-addons"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
startup: application
boot: auto
host_network: true
options:
  bridge_port: 3781
  webhook_url: ""
schema:
  bridge_port: port
  webhook_url: "str?"
map:
  - config:rw
  - addon_config:rw
homeassistant_api: true
auth_api: true
panel_icon: "mdi:whatsapp"
